apiVersion: v1
kind: Service
metadata:
  name: playing-orders
  labels:
    run: playing-orders
spec:
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      nodePort: 30030
  type: NodePort
  selector:
    app: playing-orders
