server:
  port: 9000

spring:
  datasource:
    url: ${P_MYSQL_URL}
    username: ${P_MYSQL_USERNAME}
    password: ${P_MYSQL_PASSWORD}
    validationQuery: SELECT 1
    initialize-model: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

